# Generated by Django 5.2.17 on 2026-08-27 13:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ano_nascimento', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2026)])),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_lancamento', models.DateField()),
                ('resumo', models.TextField(max_length=1500, null=True)),
                ('editora', models.CharField(max_length=100)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='acervo.autor')),
            ],
        ),
    ]
