# Generated by Django 5.2.15 on 2026-06-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('autor', models.CharField(max_length=250)),
                ('ano', models.IntegerField()),
                ('sinopse', models.TextField()),
            ],
        ),
    ]
