# Generated by Django 5.2.15 on 2026-07-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(verbose_name=255)),
                ('responsavel', models.CharField(verbose_name=255)),
                ('tempo_estimado', models.CharField(verbose_name=30)),
                ('requisitos', models.TextField()),
            ],
        ),
    ]
