# Generated by Django 5.2.15 on 2026-07-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='nome_servico',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servico',
            name='responsavel',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servico',
            name='tempo_estimado',
            field=models.CharField(max_length=30),
        ),
    ]
