# Generated by Django 5.2.15 on 2026-07-09 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_alter_servico_nome_servico_alter_servico_responsavel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servico',
            old_name='requisitos',
            new_name='descricao',
        ),
    ]
