# Generated by Django 5.2.15 on 2026-06-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('ano', models.IntegerField()),
                ('sinopse', models.TextField()),
            ],
        ),
    ]
